static struct rtl_hal_ops rtl8821au_hal_ops = {
	.init_sw_vars = rtl8821au_init_sw_vars,
	.deinit_sw_vars = rtl8821au_deinit_sw_vars,
	.read_eeprom_info = rtl8821au_read_eeprom_info,
	.interrupt_recognized = rtl8821au_interrupt_recognized,
	.hw_init = rtl8821au_hw_init,
	.hw_disable = rtl8821au_card_disable,
	.hw_suspend = rtl8821au_suspend,
	.hw_resume = rtl8821au_resume,
	.enable_interrupt = rtl8821au_enable_interrupt,
	.disable_interrupt = rtl8821au_disable_interrupt,
	.set_network_type = rtl8821au_set_network_type,
	.set_chk_bssid = rtl8821au_set_check_bssid,
	.set_qos = rtl8821au_set_qos,
	.set_bcn_reg = rtl8821au_set_beacon_related_registers,
	.set_bcn_intv = rtl8821au_set_beacon_interval,
	.update_interrupt_mask = rtl8821au_update_interrupt_mask,
	.get_hw_reg = rtl8821au_get_hw_reg,
	.set_hw_reg = rtl8821au_set_hw_reg,
	.update_rate_tbl = rtl8821au_update_hal_rate_tbl,
	.fill_tx_desc = rtl8821au_tx_fill_desc,
	.fill_tx_cmddesc = rtl8821au_tx_fill_cmddesc,
	.query_rx_desc = rtl8821au_rx_query_desc,
	.set_channel_access = rtl8821au_update_channel_access_setting,
	.radio_onoff_checking = rtl8821au_gpio_radio_on_off_checking,
	.set_bw_mode = rtl8821au_phy_set_bw_mode,
	.switch_channel = rtl8821au_phy_sw_chnl,
	.dm_watchdog = rtl8821au_dm_watchdog,
	.scan_operation_backup = rtl8821au_phy_scan_operation_backup,
	.set_rf_power_state = rtl8821au_phy_set_rf_power_state,
	.led_control = rtl8821au_led_control,
	.set_desc = rtl8821au_set_desc,
	.get_desc = rtl8821au_get_desc,
	.is_tx_desc_closed = rtl8821au_is_tx_desc_closed,
	.tx_polling = rtl8821au_tx_polling,
	.enable_hw_sec = rtl8821au_enable_hw_security_config,
	.set_key = rtl8821au_set_key,
	.init_sw_leds = rtl8821au_init_sw_leds,
	.get_bbreg = rtl8821au_phy_query_bb_reg,
	.set_bbreg = rtl8821au_phy_set_bb_reg,
	.get_rfreg = rtl8821au_phy_query_rf_reg,
	.set_rfreg = rtl8821au_phy_set_rf_reg,
	.fill_h2c_cmd = rtl8821au_fill_h2c_cmd,
	.get_btc_status = rtl8821au_get_btc_status,
	.rx_command_packet = rtl8821au_rx_command_packet,
	.add_wowlan_pattern = rtl8821au_add_wowlan_pattern,
};

static struct rtl_mod_params rtl8821au_mod_params = {
	.sw_crypto = false,
	.inactiveps = true,
	.swctrl_lps = false,
	.fwctrl_lps = true,
	.msi_support = true,
	.debug = DBG_EMERG,
	.disable_watchdog = 0,
};

static struct rtl_hal_cfg rtl8821au_hal_cfg = {
	.bar_id = 2,
	.write_readback = true,
	.name = "rtl8821au_usb",
	/* fw name is only valid for one specific device for rtl8812 we must change this */
	.fw_name = "rtlwifi/rtl8821aufw.bin",
	.ops = &rtl8821au_hal_ops,

	/* Register mapping für RTL Wifi devices must check this */

	.mod_params = &rtl8812au_mod_params,
	.maps[SYS_ISO_CTRL] = REG_SYS_ISO_CTRL,
	.maps[SYS_FUNC_EN] = REG_SYS_FUNC_EN,
	.maps[SYS_CLK] = REG_SYS_CLKR,
	.maps[MAC_RCR_AM] = AM,
	.maps[MAC_RCR_AB] = AB,
	.maps[MAC_RCR_ACRC32] = ACRC32,
	.maps[MAC_RCR_ACF] = ACF,
	.maps[MAC_RCR_AAP] = AAP,
	.maps[MAC_HIMR] = REG_HIMR,
	.maps[MAC_HIMRE] = REG_HIMRE,

	.maps[EFUSE_ACCESS] = REG_EFUSE_ACCESS,

	.maps[EFUSE_TEST] = REG_EFUSE_TEST,
	.maps[EFUSE_CTRL] = REG_EFUSE_CTRL,
	.maps[EFUSE_CLK] = 0,
	.maps[EFUSE_CLK_CTRL] = REG_EFUSE_CTRL,
	.maps[EFUSE_PWC_EV12V] = PWC_EV12V,
	.maps[EFUSE_FEN_ELDR] = FEN_ELDR,
	.maps[EFUSE_LOADER_CLK_EN] = LOADER_CLK_EN,
	.maps[EFUSE_ANA8M] = ANA8M,
	.maps[EFUSE_HWSET_MAX_SIZE] = HWSET_MAX_SIZE,
	.maps[EFUSE_MAX_SECTION_MAP] = EFUSE_MAX_SECTION,
	.maps[EFUSE_REAL_CONTENT_SIZE] = EFUSE_REAL_CONTENT_LEN,
	.maps[EFUSE_OOB_PROTECT_BYTES_LEN] = EFUSE_OOB_PROTECT_BYTES,

	.maps[RWCAM] = REG_CAMCMD,
	.maps[WCAMI] = REG_CAMWRITE,
	.maps[RCAMO] = REG_CAMREAD,
	.maps[CAMDBG] = REG_CAMDBG,
	.maps[SECR] = REG_SECCFG,
	.maps[SEC_CAM_NONE] = CAM_NONE,
	.maps[SEC_CAM_WEP40] = CAM_WEP40,
	.maps[SEC_CAM_TKIP] = CAM_TKIP,
	.maps[SEC_CAM_AES] = CAM_AES,
	.maps[SEC_CAM_WEP104] = CAM_WEP104,

	.maps[RTL_IMR_BCNDMAINT6] = IMR_BCNDMAINT6,
	.maps[RTL_IMR_BCNDMAINT5] = IMR_BCNDMAINT5,
	.maps[RTL_IMR_BCNDMAINT4] = IMR_BCNDMAINT4,
	.maps[RTL_IMR_BCNDMAINT3] = IMR_BCNDMAINT3,
	.maps[RTL_IMR_BCNDMAINT2] = IMR_BCNDMAINT2,
	.maps[RTL_IMR_BCNDMAINT1] = IMR_BCNDMAINT1,
/*	.maps[RTL_IMR_BCNDOK8] = IMR_BCNDOK8,     */   /*need check*/
	.maps[RTL_IMR_BCNDOK7] = IMR_BCNDOK7,
	.maps[RTL_IMR_BCNDOK6] = IMR_BCNDOK6,
	.maps[RTL_IMR_BCNDOK5] = IMR_BCNDOK5,
	.maps[RTL_IMR_BCNDOK4] = IMR_BCNDOK4,
	.maps[RTL_IMR_BCNDOK3] = IMR_BCNDOK3,
	.maps[RTL_IMR_BCNDOK2] = IMR_BCNDOK2,
	.maps[RTL_IMR_BCNDOK1] = IMR_BCNDOK1,
/*	.maps[RTL_IMR_TIMEOUT2] = IMR_TIMEOUT2,*/
/*	.maps[RTL_IMR_TIMEOUT1] = IMR_TIMEOUT1,*/

	.maps[RTL_IMR_TXFOVW] = IMR_TXFOVW,
	.maps[RTL_IMR_PSTIMEOUT] = IMR_PSTIMEOUT,
	.maps[RTL_IMR_BCNINT] = IMR_BCNDMAINT0,
	.maps[RTL_IMR_RXFOVW] = IMR_RXFOVW,
	.maps[RTL_IMR_RDU] = IMR_RDU,
	.maps[RTL_IMR_ATIMEND] = IMR_ATIMEND,
	.maps[RTL_IMR_BDOK] = IMR_BCNDOK0,
	.maps[RTL_IMR_MGNTDOK] = IMR_MGNTDOK,
	.maps[RTL_IMR_TBDER] = IMR_TBDER,
	.maps[RTL_IMR_HIGHDOK] = IMR_HIGHDOK,
	.maps[RTL_IMR_TBDOK] = IMR_TBDOK,
	.maps[RTL_IMR_BKDOK] = IMR_BKDOK,
	.maps[RTL_IMR_BEDOK] = IMR_BEDOK,
	.maps[RTL_IMR_VIDOK] = IMR_VIDOK,
	.maps[RTL_IMR_VODOK] = IMR_VODOK,
	.maps[RTL_IMR_ROK] = IMR_ROK,
	.maps[RTL_IBSS_INT_MASKS] = (IMR_BCNDMAINT0 | IMR_TBDOK | IMR_TBDER),

	.maps[RTL_RC_CCK_RATE1M] = DESC_RATE1M,
	.maps[RTL_RC_CCK_RATE2M] =  DESC_RATE2M,
	.maps[RTL_RC_CCK_RATE5_5M] =  DESC_RATE5_5M,
	.maps[RTL_RC_CCK_RATE11M] =  DESC_RATE11M,
	.maps[RTL_RC_OFDM_RATE6M] =  DESC_RATE6M,
	.maps[RTL_RC_OFDM_RATE9M] =  DESC_RATE9M,
	.maps[RTL_RC_OFDM_RATE12M] =  DESC_RATE12M,
	.maps[RTL_RC_OFDM_RATE18M] =  DESC_RATE18M,
	.maps[RTL_RC_OFDM_RATE24M] =  DESC_RATE24M,
	.maps[RTL_RC_OFDM_RATE36M] =  DESC_RATE36M,
	.maps[RTL_RC_OFDM_RATE48M] =  DESC_RATE48M,
	.maps[RTL_RC_OFDM_RATE54M] =  DESC_RATE54M,

	.maps[RTL_RC_HT_RATEMCS7] =  DESC_RATEMCS7,
	.maps[RTL_RC_HT_RATEMCS15] =  DESC_RATEMCS15,

	/*VHT hightest rate*/
	.maps[RTL_RC_VHT_RATE_1SS_MCS7] = DESC_RATEVHT1SS_MCS7,
	.maps[RTL_RC_VHT_RATE_1SS_MCS8] = DESC_RATEVHT1SS_MCS8,
	.maps[RTL_RC_VHT_RATE_1SS_MCS9] = DESC_RATEVHT1SS_MCS9,
	.maps[RTL_RC_VHT_RATE_2SS_MCS7] = DESC_RATEVHT2SS_MCS7,
	.maps[RTL_RC_VHT_RATE_2SS_MCS8] = DESC_RATEVHT2SS_MCS8,
	.maps[RTL_RC_VHT_RATE_2SS_MCS9] = DESC_RATEVHT2SS_MCS9,
};
